[package]
name = "ticketless-api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
sea-orm = { version = "1.0.1", features = [ "sqlx-mysql", "runtime-tokio"] }
entity = { path = "../entity" }
serde = "1.0.209"
serde_json = "1.0.127"

