//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::advertisement::Entity as Advertisement;
pub use super::event::Entity as Event;
pub use super::organization::Entity as Organization;
pub use super::ticket::Entity as Ticket;
pub use super::user::Entity as User;
